### ISSUE TITLE
Rebuild for R 4.4.1

### ISSUE THREAD

**Issue by flodel** [conda-forge/r-essentials-feedstock#11]
### Comment:

Hello, conda-forge has r-base version 4.4.1, is it possible to build and upload a compatible version of r-essentials? I hope this is the right place to ask. Thank you.

**Comment by mfansler** [comment]
Thanks for the interest! Yes, this is pending and this package will eventually have R 4.4 support. Some core devs are actively addressing several outstanding issues with the r-base feedstock in preparation for rebuilding everything for R 4.4. These will provide general improvements to the Conda R ecosystem. Once those are done then https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/6040 will be merged and R package feedstocks will start migrating to 4.4.

**Comment by flodel** [comment]
Hello again. I am wondering if you are making progress here. It seems to me the prereq you had mentioned has been completed? Thanks in advance.

**Comment by mfansler** [comment]
Yes, it is progressing. You can monitor on https://conda-forge.org/status/migration/?name=r-base44_and_m2w64-ucrt. Currently, there is a snag with `r-xml2` package that is blocking this.

**Comment by mfansler** [comment]
This was completed by https://github.com/conda-forge/r-essentials-feedstock/pull/14.
