### ISSUE TITLE
Installing steinIV triggers r-base downgrade

### ISSUE THREAD

**Issue by spittssj** [conda-forge/r-essentials-feedstock#7]
I had a similar problem and Google referred me to this issue: https://github.com/conda/conda/issues/10020

I was trying to install the <code>steinIV</code> package
to use the <code>jive.est</code> jackknife instrumental estimator to reproduce results from a journal article. I tried
to install <code>r-steinIV</code> through mamba and got the surprising install plan below -- 125 MB of updates including a downgrade
of r-base. In addition, I couldn't find a feedstock on <code>r-steinIV</code> to post the bug report there so I am asking here:

1) How do I diagnose this problem?
2) How can I get in touch with the <code>r-steinIV</code> maintainer?

Thanks.

Stephen

<details><pre><code>
(apec8213) stephenpitts@Ellacuria ps2 % mamba install r-SteinIV

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.7.12) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Looking for: ['r-steiniv']

conda-forge/osx-64       Using cache
conda-forge/noarch       Using cache
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
pkgs/main/osx-64         [====================] (00m:00s) No change
pkgs/r/osx-64            [====================] (00m:00s) No change
Transaction

  Prefix: /Users/stephenpitts/miniconda3/envs/apec8213

  Updating specs:

   - r-steiniv

  Package             Version  Build             Channel                   Size
─────────────────────────────────────────────────────────────────────────────────
  Install:
─────────────────────────────────────────────────────────────────────────────────

  r-steiniv             0.1_1  r36h6115d3f_0     pkgs/r/noarch            62 KB

  Change:
─────────────────────────────────────────────────────────────────────────────────

  r-abind               1.4_5  r40h6115d3f_1003  installed                     
  r-abind               1.4_5  r36h6115d3f_1003  conda-forge/noarch       76 KB
  r-aer                 1.2_9  r40_1             installed                     
  r-aer                 1.2_9  r36_1             conda-forge/noarch        2 MB
  r-askpass               1.1  r40h17f1fa6_2     installed                     
  r-askpass               1.1  r36h17f1fa6_2     conda-forge/osx-64       27 KB
  r-assertthat          0.2.1  r40h6115d3f_2     installed                     
  r-assertthat          0.2.1  r36h6115d3f_2     conda-forge/noarch       70 KB
  r-backports           1.2.1  r40h066c5db_0     installed                     
  r-backports           1.2.1  r36h066c5db_0     conda-forge/osx-64       97 KB
  r-base64enc           0.1_3  r40h17f1fa6_1004  installed                     
  r-base64enc           0.1_3  r36h17f1fa6_1004  conda-forge/osx-64       42 KB
  r-bdsmatrix           1.3_4  r40h17f1fa6_1     installed                     
  r-bdsmatrix           1.3_4  r36h17f1fa6_1     conda-forge/osx-64      291 KB
  r-blob                1.2.1  r40h6115d3f_1     installed                     
  r-blob                1.2.1  r36h6115d3f_1     conda-forge/noarch       63 KB
  r-boot               1.3_26  r40hc72bb7e_0     installed                     
  r-boot               1.3_26  r36hc72bb7e_0     conda-forge/noarch      634 KB
  r-brio                1.1.1  r40h066c5db_0     installed                     
  r-brio                1.1.1  r36h066c5db_0     conda-forge/osx-64       36 KB
  r-callr               3.5.1  r40h142f84f_0     installed                     
  r-callr               3.5.1  r36h142f84f_0     conda-forge/noarch      390 KB
  r-car                3.0_10  r40h6115d3f_0     installed                     
  r-car                3.0_10  r36h6115d3f_0     conda-forge/noarch        2 MB
  r-cardata             3.0_4  r40h6115d3f_0     installed                     
  r-cardata             3.0_4  r36h6115d3f_0     conda-forge/noarch        2 MB
  r-cellranger          1.1.0  r40h6115d3f_1003  installed                     
  r-cellranger          1.1.0  r36h6115d3f_1003  conda-forge/noarch      108 KB
  r-clipr               0.7.1  r40h142f84f_0     installed                     
  r-clipr               0.7.1  r36h142f84f_0     conda-forge/noarch       65 KB
  r-colorspace          2.0_0  r40h6b199c2_0     installed                     
  r-colorspace          2.0_0  r36h6b199c2_0     conda-forge/osx-64        3 MB
  r-conquer             1.0.2  r40h3e9696b_1     installed                     
  r-conquer             1.0.2  r36h4271ba9_1     conda-forge/osx-64      157 KB
  r-curl                  4.3  r40h17f1fa6_1     installed                     
  r-curl                  4.3  r36h17f1fa6_1     conda-forge/osx-64      702 KB
  r-data.table         1.13.6  r40h066c5db_0     installed                     
  r-data.table         1.13.6  r36h066c5db_0     conda-forge/osx-64        2 MB
  r-dbi                 1.1.1  r40hc72bb7e_0     installed                     
  r-dbi                 1.1.1  r36hc72bb7e_0     conda-forge/noarch      643 KB
  r-desc                1.2.0  r40h6115d3f_1003  installed                     
  r-desc                1.2.0  r36h6115d3f_1003  conda-forge/noarch      290 KB
  r-diffobj             0.3.3  r40h066c5db_0     installed                     
  r-diffobj             0.3.3  r36h066c5db_0     conda-forge/osx-64     1023 KB
  r-digest             0.6.27  r40h342fd00_0     installed                     
  r-digest             0.6.27  r36h342fd00_0     conda-forge/osx-64      205 KB
  r-ellipsis            0.3.1  r40h17f1fa6_0     installed                     
  r-ellipsis            0.3.1  r36h17f1fa6_0     conda-forge/osx-64       47 KB
  r-evaluate             0.14  r40h6115d3f_2     installed                     
  r-evaluate             0.14  r36h6115d3f_2     conda-forge/noarch       81 KB
  r-fansi               0.4.2  r40h066c5db_0     installed                     
  r-fansi               0.4.2  r36h066c5db_0     conda-forge/osx-64      187 KB
  r-farver              2.0.3  r40hc5da6b9_1     installed                     
  r-farver              2.0.3  r36hc5da6b9_1     conda-forge/osx-64        1 MB
  r-formula             1.2_4  r40h142f84f_0     installed                     
  r-formula             1.2_4  r36h142f84f_0     conda-forge/noarch      189 KB
  r-fs                  1.5.0  r40h710217c_0     installed                     
  r-fs                  1.5.0  r36h710217c_0     conda-forge/osx-64      302 KB
  r-gbrd               0.4_11  r40h6115d3f_1002  installed                     
  r-gbrd               0.4_11  r36h6115d3f_1002  conda-forge/noarch       55 KB
  r-generics            0.1.0  r40hc72bb7e_0     installed                     
  r-generics            0.1.0  r36hc72bb7e_0     conda-forge/noarch       83 KB
  r-ggplot2             3.3.3  r40hc72bb7e_0     installed                     
  r-ggplot2             3.3.3  r36hc72bb7e_0     conda-forge/noarch        4 MB
  r-glue                1.4.2  r40h066c5db_0     installed                     
  r-glue                1.4.2  r36h800e0f2_0     conda-forge/osx-64      140 KB
  r-gtable              0.3.0  r40h6115d3f_3     installed                     
  r-gtable              0.3.0  r36h6115d3f_3     conda-forge/noarch      423 KB
  r-haven               2.3.1  r40hee97c7f_0     installed                     
  r-haven               2.3.1  r36hee97c7f_0     conda-forge/osx-64      367 KB
  r-highr                 0.8  r40h6115d3f_2     installed                     
  r-highr                 0.8  r36h6115d3f_2     conda-forge/noarch       58 KB
  r-hms                 1.0.0  r40hc72bb7e_0     installed                     
  r-hms                 1.0.0  r36hc72bb7e_0     conda-forge/noarch      106 KB
  r-htmltools         0.5.1.1  r40h815b84a_0     installed                     
  r-htmltools         0.5.1.1  r36h815b84a_0     conda-forge/osx-64      243 KB
  r-httr                1.4.2  r40h6115d3f_0     installed                     
  r-httr                1.4.2  r36h6115d3f_0     conda-forge/noarch      493 KB
  r-isoband             0.2.3  r40h1019320_0     installed                     
  r-isoband             0.2.3  r36h1019320_0     conda-forge/osx-64        2 MB
  r-jsonlite            1.7.2  r40h066c5db_0     installed                     
  r-jsonlite            1.7.2  r36h066c5db_0     conda-forge/osx-64      458 KB
  r-labeling            0.4.2  r40h142f84f_0     installed                     
  r-labeling            0.4.2  r36h142f84f_0     conda-forge/noarch       67 KB
  r-lattice           0.20_41  r40h066c5db_3     installed                     
  r-lattice           0.20_41  r36h066c5db_3     conda-forge/osx-64        1 MB
  r-lifecycle           0.2.0  r40h6115d3f_1     installed                     
  r-lifecycle           0.2.0  r36h6115d3f_1     conda-forge/noarch      112 KB
  r-lme4               1.1_26  r40h1019320_0     installed                     
  r-lme4               1.1_26  r36h1019320_0     conda-forge/osx-64        4 MB
  r-lmtest             0.9_38  r40h43cf36c_1     installed                     
  r-lmtest             0.9_38  r36h43cf36c_1     conda-forge/osx-64      408 KB
  r-lubridate         1.7.9.2  r40h1019320_0     installed                     
  r-lubridate         1.7.9.2  r36h1019320_0     conda-forge/osx-64        1 MB
  r-magrittr            2.0.1  r40h066c5db_1     installed                     
  r-magrittr            2.0.1  r36he27d7ee_1     conda-forge/osx-64      210 KB
  r-maptools            1.0_2  r40h800e0f2_0     installed                     
  r-maptools            1.0_2  r36h800e0f2_0     conda-forge/osx-64        2 MB
  r-markdown              1.1  r40h066c5db_1     installed                     
  r-markdown              1.1  r36h066c5db_1     conda-forge/osx-64      140 KB
  r-mass               7.3_53  r40h066c5db_0     installed                     
  r-mass               7.3_53  r36h800e0f2_0     conda-forge/osx-64        1 MB
  r-matrix              1.3_2  r40he51b063_0     installed                     
  r-matrix              1.3_2  r36he51b063_0     conda-forge/osx-64        4 MB
  r-matrixmodels        0.4_1  r40h6115d3f_1003  installed                     
  r-matrixmodels        0.4_1  r36h6115d3f_1003  conda-forge/noarch      354 KB
  r-maxlik              1.4_6  r40hc72bb7e_0     installed                     
  r-maxlik              1.4_6  r36hc72bb7e_0     conda-forge/noarch      682 KB
  r-mgcv               1.8_33  r40hb6d66fe_0     installed                     
  r-mgcv               1.8_33  r36hb6d66fe_0     conda-forge/osx-64        3 MB
  r-mime                  0.9  r40h066c5db_1     installed                     
  r-mime                  0.9  r36h066c5db_1     conda-forge/osx-64       50 KB
  r-minqa               1.2.4  r40ha6353f9_1006  installed                     
  r-minqa               1.2.4  r36ha6353f9_1006  conda-forge/osx-64      138 KB
  r-misctools          0.6_26  r40h6115d3f_1     installed                     
  r-misctools          0.6_26  r36h6115d3f_1     conda-forge/noarch       98 KB
  r-modelr              0.1.8  r40h6115d3f_0     installed                     
  r-modelr              0.1.8  r36h6115d3f_0     conda-forge/noarch      218 KB
  r-munsell             0.5.0  r40h6115d3f_1003  installed                     
  r-munsell             0.5.0  r36h6115d3f_1003  conda-forge/noarch      246 KB
  r-nloptr            1.2.2.2  r40hc5da6b9_0     installed                     
  r-nloptr            1.2.2.2  r36hc5da6b9_0     conda-forge/osx-64      536 KB
  r-nnet               7.3_15  r40h066c5db_0     installed                     
  r-nnet               7.3_15  r36h066c5db_0     conda-forge/osx-64      134 KB
  r-numderiv       2016.8_1.1  r40h6115d3f_3     installed                     
  r-numderiv       2016.8_1.1  r36h6115d3f_3     conda-forge/noarch      126 KB
  r-openssl             1.4.3  r40ha713f70_0     installed                     
  r-openssl             1.4.3  r36ha713f70_0     conda-forge/osx-64        1 MB
  r-openxlsx            4.2.3  r40h342fd00_0     installed                     
  r-openxlsx            4.2.3  r36h342fd00_0     conda-forge/osx-64        2 MB
  r-pbkrtest          0.5_0.1  r40hc72bb7e_0     installed                     
  r-pbkrtest          0.5_0.1  r36hc72bb7e_0     conda-forge/noarch      358 KB
  r-pillar              1.4.7  r40hc72bb7e_0     installed                     
  r-pillar              1.4.7  r36hc72bb7e_0     conda-forge/noarch      194 KB
  r-pkgbuild            1.2.0  r40hc72bb7e_0     installed                     
  r-pkgbuild            1.2.0  r36hc72bb7e_0     conda-forge/noarch      157 KB
  r-pkgconfig           2.0.3  r40h6115d3f_1     installed                     
  r-pkgconfig           2.0.3  r36h6115d3f_1     conda-forge/noarch       24 KB
  r-pkgload             1.1.0  r40hc5da6b9_0     installed                     
  r-pkgload             1.1.0  r36hc5da6b9_0     conda-forge/osx-64      166 KB
  r-plm                 2.4_0  r40hc72bb7e_0     installed                     
  r-plm                 2.4_0  r36hc72bb7e_0     conda-forge/noarch        2 MB
  r-plyr                1.8.6  r40hc5da6b9_1     installed                     
  r-plyr                1.8.6  r36hc5da6b9_1     conda-forge/osx-64      831 KB
  r-praise              1.0.0  r40h6115d3f_1004  installed                     
  r-praise              1.0.0  r36h6115d3f_1004  conda-forge/noarch       23 KB
  r-prettyunits         1.1.1  r40h6115d3f_1     installed                     
  r-prettyunits         1.1.1  r36h6115d3f_1     conda-forge/noarch       41 KB
  r-processx            3.4.5  r40he27d7ee_0     installed                     
  r-processx            3.4.5  r36he27d7ee_0     conda-forge/osx-64      285 KB
  r-progress            1.2.2  r40h6115d3f_2     installed                     
  r-progress            1.2.2  r36h6115d3f_2     conda-forge/noarch       90 KB
  r-ps                  1.5.0  r40h066c5db_0     installed                     
  r-ps                  1.5.0  r36h066c5db_0     conda-forge/osx-64      282 KB
  r-purrr               0.3.4  r40h17f1fa6_1     installed                     
  r-purrr               0.3.4  r36h17f1fa6_1     conda-forge/osx-64      408 KB
  r-quantreg             5.83  r40h2704daa_0     installed                     
  r-quantreg             5.83  r36h2704daa_0     conda-forge/osx-64        2 MB
  r-r6                  2.5.0  r40hc72bb7e_0     installed                     
  r-r6                  2.5.0  r36hc72bb7e_0     conda-forge/noarch       89 KB
  r-rbibutils             2.0  r40he27d7ee_0     installed                     
  r-rbibutils             2.0  r36he27d7ee_0     conda-forge/osx-64      534 KB
  r-rcolorbrewer        1.1_2  r40h6115d3f_1003  installed                     
  r-rcolorbrewer        1.1_2  r36h6115d3f_1003  conda-forge/noarch       59 KB
  r-rcpp                1.0.6  r40h815b84a_0     installed                     
  r-rcpp                1.0.6  r36h815b84a_0     conda-forge/osx-64        2 MB
  r-rcpparmadillo  0.10.1.2.2  r40hbe96a68_0     installed                     
  r-rcpparmadillo  0.10.1.2.2  r36hbe96a68_0     conda-forge/osx-64        1 MB
  r-rcppeigen       0.3.3.9.1  r40hbe96a68_0     installed                     
  r-rcppeigen       0.3.3.9.1  r36hbe96a68_0     conda-forge/osx-64        2 MB
  r-rdpack                2.1  r40hc72bb7e_0     installed                     
  r-rdpack                2.1  r36hc72bb7e_0     conda-forge/noarch      919 KB
  r-readr               1.4.0  r40h342fd00_0     installed                     
  r-readr               1.4.0  r36h342fd00_0     conda-forge/osx-64      810 KB
  r-readxl              1.3.1  r40hee97c7f_4     installed                     
  r-readxl              1.3.1  r36hee97c7f_4     conda-forge/osx-64      867 KB
  r-rematch             1.0.1  r40h6115d3f_1003  installed                     
  r-rematch             1.0.1  r36h6115d3f_1003  conda-forge/noarch       19 KB
  r-rematch2            2.1.2  r40h6115d3f_1     installed                     
  r-rematch2            2.1.2  r36h6115d3f_1     conda-forge/noarch       52 KB
  r-reshape2            1.4.4  r40hc5da6b9_1     installed                     
  r-reshape2            1.4.4  r36hc5da6b9_1     conda-forge/osx-64      126 KB
  r-rio                0.5.16  r40h6115d3f_1002  installed                     
  r-rio                0.5.16  r36h6115d3f_1002  conda-forge/noarch      493 KB
  r-rlang              0.4.10  r40h066c5db_0     installed                     
  r-rlang              0.4.10  r36h066c5db_0     conda-forge/osx-64        1 MB
  r-rmarkdown             2.6  r40hc72bb7e_0     installed                     
  r-rmarkdown             2.6  r36hc72bb7e_0     conda-forge/noarch        3 MB
  r-rprojroot           2.0.2  r40hc72bb7e_0     installed                     
  r-rprojroot           2.0.2  r36hc72bb7e_0     conda-forge/noarch      110 KB
  r-rstudioapi           0.13  r40hc72bb7e_0     installed                     
  r-rstudioapi           0.13  r36hc72bb7e_0     conda-forge/noarch      281 KB
  r-rvest               0.3.6  r40h6115d3f_0     installed                     
  r-rvest               0.3.6  r36h6115d3f_0     conda-forge/noarch        1 MB
  r-sandwich            3.0_0  r40h142f84f_0     installed                     
  r-sandwich            3.0_0  r36h142f84f_0     conda-forge/noarch        1 MB
  r-scales              1.1.1  r40h6115d3f_0     installed                     
  r-scales              1.1.1  r36h6115d3f_0     conda-forge/noarch      558 KB
  r-selectr             0.4_2  r40h6115d3f_1     installed                     
  r-selectr             0.4_2  r36h6115d3f_1     conda-forge/noarch      475 KB
  r-sp                  1.4_5  r40h066c5db_0     installed                     
  r-sp                  1.4_5  r36h066c5db_0     conda-forge/osx-64        2 MB
  r-sparsem              1.78  r40h43cf36c_2     installed                     
  r-sparsem              1.78  r36h43cf36c_2     conda-forge/osx-64        1 MB
  r-spatial            7.3_13  r40h066c5db_0     installed                     
  r-spatial            7.3_13  r36h066c5db_0     conda-forge/osx-64      156 KB
  r-stargazer           5.2.2  r40h6115d3f_2     installed                     
  r-stargazer           5.2.2  r36h6115d3f_2     conda-forge/noarch      626 KB
  r-statmod            1.4.35  r40h508aa58_1     installed                     
  r-statmod            1.4.35  r36h508aa58_1     conda-forge/osx-64      279 KB
  r-stringi             1.5.3  r40h9aeca8d_1     installed                     
  r-stringi             1.5.3  r36h9aeca8d_1     conda-forge/osx-64      778 KB
  r-stringr             1.4.0  r40h6115d3f_2     installed                     
  r-stringr             1.4.0  r36h6115d3f_2     conda-forge/noarch      209 KB
  r-survival            3.2_7  r40h800e0f2_0     installed                     
  r-survival            3.2_7  r36hf6ff476_0     conda-forge/osx-64        8 MB
  r-sys                   3.4  r40h800e0f2_0     installed                     
  r-sys                   3.4  r36h800e0f2_0     conda-forge/osx-64       46 KB
  r-testthat            3.0.1  r40h815b84a_0     installed                     
  r-testthat            3.0.1  r36h815b84a_0     conda-forge/osx-64        2 MB
  r-tidyr               1.1.2  r40h710217c_0     installed                     
  r-tidyr               1.1.2  r36h710217c_0     conda-forge/osx-64      788 KB
  r-tidyselect          1.1.0  r40h6115d3f_0     installed                     
  r-tidyselect          1.1.0  r36h6115d3f_0     conda-forge/osx-64      205 KB
  r-tidyverse           1.3.0  r40h6115d3f_2     installed                     
  r-tidyverse           1.3.0  r36h6115d3f_2     conda-forge/noarch      452 KB
  r-tinytex              0.29  r40hc72bb7e_0     installed                     
  r-tinytex              0.29  r36hc72bb7e_0     conda-forge/noarch      121 KB
  r-utf8                1.1.4  r40h17f1fa6_1003  installed                     
  r-utf8                1.1.4  r36h17f1fa6_1003  conda-forge/osx-64      155 KB
  r-vctrs               0.3.6  r40h066c5db_0     installed                     
  r-vctrs               0.3.6  r36h066c5db_0     conda-forge/osx-64        1 MB
  r-viridislite         0.3.0  r40h6115d3f_1003  installed                     
  r-viridislite         0.3.0  r36h6115d3f_1003  conda-forge/noarch       64 KB
  r-waldo               0.2.3  r40hc72bb7e_0     installed                     
  r-waldo               0.2.3  r36hc72bb7e_0     conda-forge/noarch       79 KB
  r-whisker               0.4  r40h6115d3f_1     installed                     
  r-whisker               0.4  r36h6115d3f_1     conda-forge/noarch       80 KB
  r-withr               2.4.1  r40hc72bb7e_0     installed                     
  r-withr               2.4.1  r36hc72bb7e_0     conda-forge/noarch      217 KB
  r-xfun                 0.20  r40h066c5db_0     installed                     
  r-xfun                 0.20  r36h066c5db_0     conda-forge/osx-64      296 KB
  r-xml2                1.3.2  r40hc5da6b9_1     installed                     
  r-xml2                1.3.2  r36hc5da6b9_1     conda-forge/osx-64      249 KB
  r-yaml                2.2.1  r40h066c5db_1     installed                     
  r-yaml                2.2.1  r36h066c5db_1     conda-forge/osx-64      112 KB
  r-zeallot             0.1.0  r40h6115d3f_1002  installed                     
  r-zeallot             0.1.0  r36h6115d3f_1002  conda-forge/noarch       62 KB
  r-zip                 2.1.1  r40h800e0f2_0     installed                     
  r-zip                 2.1.1  r36h800e0f2_0     conda-forge/osx-64      147 KB
  r-zoo                 1.8_8  r40h17f1fa6_0     installed                     
  r-zoo                 1.8_8  r36h17f1fa6_0     conda-forge/osx-64        1 MB

  Upgrade:
─────────────────────────────────────────────────────────────────────────────────

  ca-certificates   2020.12.5  h033912b_0        installed                     
  ca-certificates   2021.1.19  hecd8cb5_0        pkgs/main/osx-64        Cached
  r-broom               0.7.3  r40hc72bb7e_0     installed                     
  r-broom               0.7.4  r36hc72bb7e_0     conda-forge/noarch        2 MB
  r-cli                 2.2.0  r40hc72bb7e_0     installed                     
  r-cli                 2.3.0  r36hc72bb7e_0     conda-forge/noarch      470 KB
  r-cpp11               0.2.5  r40hc72bb7e_0     installed                     
  r-cpp11               0.2.6  r36hc72bb7e_0     conda-forge/noarch      154 KB
  r-crayon              1.3.4  r40h6115d3f_1003  installed                     
  r-crayon              1.4.0  r36hc72bb7e_0     conda-forge/noarch      145 KB
  r-dbplyr              2.0.0  r40hc72bb7e_0     installed                     
  r-dbplyr              2.1.0  r36hc72bb7e_0     conda-forge/noarch      821 KB
  r-dplyr               1.0.3  r40h815b84a_0     installed                     
  r-dplyr               1.0.4  r36h4efb63e_0     conda-forge/osx-64        1 MB
  r-forcats             0.5.0  r40h6115d3f_1     installed                     
  r-forcats             0.5.1  r36hc72bb7e_0     conda-forge/noarch      378 KB
  r-knitr                1.30  r40h6115d3f_0     installed                     
  r-knitr                1.31  r36hc72bb7e_0     conda-forge/noarch        1 MB
  r-matrixstats        0.57.0  r40h066c5db_0     installed                     
  r-matrixstats        0.58.0  r36hf6ff476_0     conda-forge/osx-64      846 KB
  r-nlme              3.1_151  r40h1a6e9bf_0     installed                     
  r-nlme              3.1_152  r36h59bb11e_0     conda-forge/osx-64        2 MB
  r-reprex              0.3.0  r40h6115d3f_2     installed                     
  r-reprex              1.0.0  r36hc72bb7e_0     conda-forge/noarch      483 KB
  r-tibble              3.0.5  r40h066c5db_0     installed                     
  r-tibble              3.0.6  r36hf6ff476_0     conda-forge/osx-64      747 KB

  Downgrade:
─────────────────────────────────────────────────────────────────────────────────

  r-base                4.0.3  h2b2b636_4        installed                     
  r-base                3.6.3  h2b2b636_6        conda-forge/osx-64       23 MB
  r-foreign            0.8_81  r40h066c5db_0     installed                     
  r-foreign            0.8_76  r36h17f1fa6_1     conda-forge/osx-64      264 KB

  Summary:

  Install: 1 packages
  Change: 126 packages
  Upgrade: 13 packages
  Downgrade: 2 packages

  Total download: 125 MB

─────────────────────────────────────────────────────────────────────────────────

Confirm changes: [Y/n] n
</code></pre>

_Originally posted by @spittssj in https://github.com/conda/conda/issues/10020#issuecomment-775620238_

**Comment by dpryan79** [comment]
r-steinIV isn't provided by conda-forge (it's from anaconda) and is built for R-3.6, so it will have to downgrade to that. If you want it built for more recent versions of R then please add it to conda-forge.

**Comment by spittssj** [comment]
Ah -- somehow I missed that detail that it's an Anaconda package. That explains why I couldn't find it a feedstock on conda-forge. Honestly, the JIVE estimator is not that great (Stata's is much better and it's a rarely used econometric method anyway) so it turns out I don't need it for my project. Thanks for your help.
